apiVersion: v1
kind: Service
metadata:
  name: dockyards-backend
spec:
  ports:
  - name: public
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: private
    port: 9001
    protocol: TCP
    targetPort: 9001
  - name: webhook
    port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    app.kubernetes.io/name: dockyards-backend
    app.kubernetes.io/part-of: dockyards
  type: ClusterIP
