# Copyright 2024 Sudo Sweden AB
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

image: docker.io/library/golang:1.23.1

definitions:
  steps:
  - step: &default
      name: default
      script:
      - echo "export VERSION=$(git branch --show-current)-$(git rev-parse --short HEAD)-$(date +%s)" >> env.sh
      - echo "export IMAGE=public.ecr.aws/sudosweden/dockyards-backend" >> env.sh
      - echo "export REVISION=$(git branch --show-current)@$(git rev-parse --show-object-format):$(git rev-parse HEAD)" >> env.sh
      artifacts:
      - env.sh
  - step: &test
      name: test
      script:
      - go install sigs.k8s.io/controller-runtime/tools/setup-envtest@release-0.19
      - source <(setup-envtest use --print env 1.31.0)
      - go test ./... -v
  - step: &build
      name: build
      script:
      - source env.sh
      - go install cuelang.org/go/cmd/cue@v0.10.0
      - docker build . --file Containerfile --tag dockyards-backend
      - docker save dockyards-backend --output dockyards-backend.tar
      - cue eval hack/kustomization.cue --inject "name=${IMAGE}" --inject "tag=${VERSION}" --out yaml --outfile config/kustomization.yaml
      services:
      - docker
      caches:
      - docker
      artifacts:
      - dockyards-backend.tar
      - config/kustomization.yaml
  - step: &push
      name: push
      script:
      - source env.sh
      - echo "${TOKEN}" | docker login --username AWS --password-stdin public.ecr.aws
      - docker load --input dockyards-backend.tar
      - docker tag dockyards-backend "${IMAGE}:${VERSION}"
      - docker push "${IMAGE}:${VERSION}"
      services:
      - docker
  - step: &vendor
      name: vendor
      script:
      - export GOPRIVATE=bitbucket.org/sudosweden
      - git config --global url."ssh://git@bitbucket.org/".insteadOf "https://bitbucket.org/"
      - go mod vendor
      artifacts:
      - vendor/**
  - step: &ecr-login
      name: ecr-login
      oidc: true
      image: docker.io/amazon/aws-cli:2.22.7
      script:
      - echo $BITBUCKET_STEP_OIDC_TOKEN > /tmp/web-identity-token
      - aws configure --profile bitbucket set region eu-north-1
      - aws configure --profile bitbucket set role_arn arn:aws:iam::075899289117:role/BitbucketPipelinesDockyardsBackendPublic
      - aws configure --profile bitbucket set web_identity_token_file /tmp/web-identity-token
      - echo "export TOKEN=$(aws ecr-public get-login-password --profile bitbucket --region us-east-1)" >> env.sh
      artifacts:
      - env.sh
  - step: &flux
      name: flux
      image: ghcr.io/fluxcd/flux-cli:v2.4.0
      script:
      - source env.sh
      - flux push artifact "oci://${IMAGE}:${VERSION}-manifests" --path config --source "$BITBUCKET_GIT_HTTP_ORIGIN" --revision "${REVISION}" --creds "AWS:${TOKEN}"
  - step: &tag
      name: tag
      script:
      - echo "export VERSION=$(git describe --exact-match)" >> env.sh
      - echo "export IMAGE=public.ecr.aws/sudosweden/dockyards-backend" >> env.sh
      - echo "export REVISION=$(git branch --show-current)@$(git rev-parse --show-object-format):$(git rev-parse HEAD)" >> env.sh
      artifacts:
      - env.sh
  - step: &lint
      name: lint
      script:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.62.0
      - golangci-lint run

pipelines:
  default:
  - step: *default
  - step: *vendor
  - parallel:
      steps:
      - step: *test
      - step: *lint
  - step: *build
  - step: *ecr-login
  - step: *push
  - step: *flux
  tags:
    'v*':
    - step: *tag
    - step: *vendor
    - parallel:
        steps:
        - step: *test
        - step: *lint
    - step: *build
    - step: *ecr-login
    - step: *push
    - step: *flux
