image: docker.io/library/golang:1.21

definitions:
  steps:
  - step: &default
      name: default
      script:
      - echo "export VERSION=$(git branch --show-current)-$(git rev-parse --short HEAD)-$(date +%s)" >> env.sh
      - echo "export IMAGE=075899289117.dkr.ecr.eu-north-1.amazonaws.com/dockyards-backend" >> env.sh
      - echo "export REVISION=$(git branch --show-current)@$(git rev-parse --show-object-format):$(git rev-parse HEAD)" >> env.sh
      artifacts:
      - env.sh
  - step: &test
      name: test
      script:
      - go test ./... -v
  - step: &build
      name: build
      script:
      - source env.sh
      - go install cuelang.org/go/cmd/cue@v0.7.1
      - docker build . --file Containerfile --tag dockyards-backend
      - docker save dockyards-backend --output dockyards-backend.tar
      - cue eval hack/kustomization.cue --inject "name=${IMAGE}" --inject "tag=${VERSION}" --out yaml --outfile config/kustomization.yaml
      services:
      - docker
      caches:
      - docker
      artifacts:
      - dockyards-backend.tar
      - config/kustomization.yaml
  - step: &push
      name: push
      script:
      - cat env.sh
      - source env.sh
      - echo "${TOKEN}" | docker login --username "AWS" --password-stdin "075899289117.dkr.ecr.eu-north-1.amazonaws.com"
      - docker load --input dockyards-backend.tar
      - docker tag dockyards-backend "${IMAGE}:${VERSION}"
      - docker push "${IMAGE}:${VERSION}"
      services:
      - docker
  - step: &vendor
      name: vendor
      script:
      - export GOPRIVATE=bitbucket.org/sudosweden
      - git config --global url."ssh://git@bitbucket.org/".insteadOf "https://bitbucket.org/"
      - go mod vendor
      artifacts:
      - vendor/**
  - step: &ecr-login
      name: ecr-login
      oidc: true
      image: docker.io/amazon/aws-cli:2.11.8
      script:
      - echo $BITBUCKET_STEP_OIDC_TOKEN > /tmp/web-identity-token
      - aws configure --profile bitbucket set region eu-north-1
      - aws configure --profile bitbucket set role_arn arn:aws:iam::075899289117:role/BitbucketPipelinesBackend
      - aws configure --profile bitbucket set web_identity_token_file /tmp/web-identity-token
      - echo "export TOKEN=$(aws ecr get-login-password --profile bitbucket)" >> env.sh
      artifacts:
      - env.sh
  - step: &flux
      name: flux
      image: ghcr.io/fluxcd/flux-cli:v2.2.3
      script:
      - source env.sh
      - flux push artifact "oci://${IMAGE}:${VERSION}-manifests" --path config --source "$BITBUCKET_GIT_HTTP_ORIGIN" --revision "${REVISION}" --creds "AWS:${TOKEN}"
  - step: &tag
      name: tag
      script:
      - echo "export VERSION=$(git describe --exact-match)" >> env.sh
      - echo "export IMAGE=075899289117.dkr.ecr.eu-north-1.amazonaws.com/dockyards-backend" >> env.sh
      - echo "export REVISION=$(git branch --show-current)@$(git rev-parse --show-object-format):$(git rev-parse HEAD)" >> env.sh
      artifacts:
      - env.sh

pipelines:
  default:
  - step: *default
  - step: *vendor
  - step: *ecr-login
  - step: *test
  - step: *build
  - step: *push
  - step: *flux
  tags:
    'v*':
    - step: *tag
    - step: *vendor
    - step: *ecr-login
    - step: *test
    - step: *build
    - step: *push
    - step: *flux
