image: atlassian/default-image:3

definitions:
  steps:
  - step: &environment
      name: environment
      image: docker.io/library/golang:1.21
      script:
      - git fetch --tags
      - echo "export IMAGE_NAME=$BITBUCKET_REPO_SLUG" >> env.sh
      - echo "export VERSION=$BITBUCKET_BRANCH-$(git describe --always --dirty)-$(date +%s)" >> env.sh
      - echo "export IMAGE=075899289117.dkr.ecr.eu-north-1.amazonaws.com/dockyards-backend" >> env.sh
      - cat env.sh
      artifacts:
      - env.sh
  - step: &test
      name: test
      image: docker.io/library/golang:1.21
      script:
      - go test ./... -v
  - step: &build
      name: build
      script:
      - source env.sh
      - docker build . --file Containerfile --tag ${IMAGE_NAME}
      - docker save ${IMAGE_NAME} --output "${IMAGE_NAME}.tar"
      services:
      - docker
      caches:
      - docker
      artifacts:
      - "*.tar"
  - step: &push
      name: push
      image: docker.io/amazon/aws-cli:2.11.8
      script:
      - source env.sh
      - aws ecr get-login-password | docker login --username "AWS" --password-stdin "075899289117.dkr.ecr.eu-north-1.amazonaws.com"
      - docker load --input "${IMAGE_NAME}.tar"
      - docker tag "${IMAGE_NAME}" "${IMAGE}:${VERSION}"
      - docker push "${IMAGE}:${VERSION}"
      services:
      - docker

pipelines:
  default:
  - step: *environment
  - step: *test
  - step: *build
  - step: *push
