version: '3.8'
networks:
  backend:
services:
  DB:
    image: postgres:15.2-alpine3.17
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      # POSTGRES_USER defaults to postgres check https://hub.docker.com/_/postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  Rancher:
    image: rancher/rancher:latest
    networks:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "rancher-data:/var/lib/rancher"
    privileged: true
volumes:
  rancher-data:
