// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package v1

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for DeploymentType.
const (
	DeploymentTypeContainerImage DeploymentType = "container_image"
	DeploymentTypeHelm           DeploymentType = "helm"
	DeploymentTypeKustomize      DeploymentType = "kustomize"
)

// Defines values for DeploymentStatusHealth.
const (
	DeploymentStatusHealthError   DeploymentStatusHealth = "error"
	DeploymentStatusHealthHealthy DeploymentStatusHealth = "healthy"
	DeploymentStatusHealthWarning DeploymentStatusHealth = "warning"
)

// App defines model for app.
type App struct {
	AppSteps    *[]AppStep `json:"app_steps,omitempty"`
	Description *string    `json:"description,omitempty"`
	Icon        *string    `json:"icon,omitempty"`
	Id          string     `json:"id"`
	Name        string     `json:"name"`
}

// AppStep defines model for app_step.
type AppStep struct {
	Name        string        `json:"name"`
	StepOptions *[]StepOption `json:"step_options,omitempty"`
}

// Cluster defines model for cluster.
type Cluster struct {
	CreatedAt    time.Time  `json:"created_at"`
	Id           string     `json:"id"`
	Name         string     `json:"name"`
	NodeCount    int        `json:"node_count"`
	NodePools    []NodePool `json:"node_pools"`
	Organization string     `json:"organization"`
	State        string     `json:"state"`
	Version      string     `json:"version"`
}

// ClusterOptions defines model for cluster_options.
type ClusterOptions struct {
	IngressProvider   *string            `json:"ingress_provider,omitempty"`
	Name              string             `json:"name"`
	NoClusterApps     *bool              `json:"no_cluster_apps,omitempty"`
	NoIngressProvider *bool              `json:"no_ingress_provider,omitempty"`
	NodePoolOptions   *[]NodePoolOptions `json:"node_pool_options,omitempty"`
	SingleNode        *bool              `json:"single_node,omitempty"`
	Version           *string            `json:"version,omitempty"`
}

// ClusterOverview defines model for cluster_overview.
type ClusterOverview struct {
	Deployments *[]DeploymentOverview `json:"deployments,omitempty"`
	Id          string                `json:"id"`
	Name        string                `json:"name"`
}

// Credential defines model for credential.
type Credential struct {
	Data         *map[string]interface{} `json:"data,omitempty"`
	Id           string                  `json:"id"`
	Name         string                  `json:"name"`
	Organization string                  `json:"organization"`
}

// Deployment defines model for deployment.
type Deployment struct {
	ClusterId      string                  `json:"cluster_id"`
	ContainerImage *string                 `json:"container_image,omitempty"`
	CredentialId   *string                 `json:"credential_id,omitempty"`
	HelmChart      *string                 `json:"helm_chart,omitempty"`
	HelmRepository *string                 `json:"helm_repository,omitempty"`
	HelmValues     *map[string]interface{} `json:"helm_values,omitempty"`
	HelmVersion    *string                 `json:"helm_version,omitempty"`
	Id             string                  `json:"id"`
	Kustomize      *map[string][]byte      `json:"kustomize,omitempty"`
	Name           *string                 `json:"name,omitempty"`
	Namespace      *string                 `json:"namespace,omitempty"`
	Port           *int                    `json:"port,omitempty"`
	Status         *DeploymentStatus       `json:"status,omitempty"`
	Type           DeploymentType          `json:"type"`
}

// DeploymentType defines model for Deployment.Type.
type DeploymentType string

// DeploymentOverview defines model for deployment_overview.
type DeploymentOverview struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// DeploymentStatus defines model for deployment_status.
type DeploymentStatus struct {
	CreatedAt    time.Time               `json:"created_at"`
	DeploymentId string                  `json:"deployment_id"`
	Health       *DeploymentStatusHealth `json:"health,omitempty"`
	Id           string                  `json:"id"`
	State        *string                 `json:"state,omitempty"`
	Urls         *[]string               `json:"urls,omitempty"`
}

// DeploymentStatusHealth defines model for DeploymentStatus.Health.
type DeploymentStatusHealth string

// Login defines model for login.
type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// Node defines model for node.
type Node struct {
	Id    string `json:"id"`
	Name  string `json:"name"`
	State string `json:"state"`
}

// NodePool defines model for node_pool.
type NodePool struct {
	ClusterId                  string `json:"cluster_id"`
	ControlPlane               *bool  `json:"control_plane,omitempty"`
	ControlPlaneComponentsOnly *bool  `json:"control_plane_components_only,omitempty"`
	CpuCount                   int    `json:"cpu_count"`
	DiskSizeGb                 int    `json:"disk_size_gb"`
	Etcd                       *bool  `json:"etcd,omitempty"`
	Id                         string `json:"id"`
	LoadBalancer               *bool  `json:"load_balancer,omitempty"`
	Name                       string `json:"name"`
	Nodes                      []Node `json:"nodes"`
	Quantity                   int    `json:"quantity"`
	RamSizeMb                  int    `json:"ram_size_mb"`
}

// NodePoolOptions defines model for node_pool_options.
type NodePoolOptions struct {
	ControlPlane               *bool  `json:"control_plane,omitempty"`
	ControlPlaneComponentsOnly *bool  `json:"control_plane_components_only,omitempty"`
	CpuCount                   *int   `json:"cpu_count,omitempty"`
	DiskSizeGb                 *int   `json:"disk_size_gb,omitempty"`
	Etcd                       *bool  `json:"etcd,omitempty"`
	LoadBalancer               *bool  `json:"load_balancer,omitempty"`
	Name                       string `json:"name"`
	Quantity                   int    `json:"quantity"`
	RamSizeMb                  *int   `json:"ram_size_mb,omitempty"`
}

// Options defines model for options.
type Options struct {
	NodePoolOptions []NodePoolOptions `json:"node_pool_options"`
	SingleNode      bool              `json:"single_node"`
	Version         []string          `json:"version"`
}

// Organization defines model for organization.
type Organization struct {
	CreatedAt   time.Time `json:"created_at"`
	DisplayName *string   `json:"display_name,omitempty"`
	Id          string    `json:"id"`
	Name        string    `json:"name"`
	UpdatedAt   time.Time `json:"updated_at"`
}

// OrganizationOverview defines model for organization_overview.
type OrganizationOverview struct {
	Clusters *[]ClusterOverview `json:"clusters,omitempty"`
	Id       string             `json:"id"`
	Name     string             `json:"name"`
	Users    *[]UserOverview    `json:"users,omitempty"`
}

// Overview defines model for overview.
type Overview struct {
	Organizations []OrganizationOverview `json:"organizations"`
}

// StepOption defines model for step_option.
type StepOption struct {
	Default     *string   `json:"default,omitempty"`
	DisplayName *string   `json:"display_name,omitempty"`
	Hidden      *bool     `json:"hidden,omitempty"`
	JsonPointer *string   `json:"json_pointer,omitempty"`
	Managed     *bool     `json:"managed,omitempty"`
	Selection   *[]string `json:"selection,omitempty"`
	Tags        *[]string `json:"tags,omitempty"`
	Toggle      *[]string `json:"toggle,omitempty"`
	Type        *string   `json:"type,omitempty"`
}

// Tokens defines model for tokens.
type Tokens struct {
	AccessToken  string `json:"AccessToken"`
	RefreshToken string `json:"RefreshToken"`
}

// User defines model for user.
type User struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Email     string     `json:"email"`
	Id        string     `json:"id"`
	Name      string     `json:"name"`
	Password  *string    `json:"password,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// UserOverview defines model for user_overview.
type UserOverview struct {
	Email string `json:"email"`
	Id    string `json:"id"`
}

// CreateDeploymentJSONRequestBody defines body for CreateDeployment for application/json ContentType.
type CreateDeploymentJSONRequestBody = Deployment

// CreateNodePoolJSONRequestBody defines body for CreateNodePool for application/json ContentType.
type CreateNodePoolJSONRequestBody = NodePoolOptions

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = Login

// CreateClusterJSONRequestBody defines body for CreateCluster for application/json ContentType.
type CreateClusterJSONRequestBody = ClusterOptions

// CreateCredentialJSONRequestBody defines body for CreateCredential for application/json ContentType.
type CreateCredentialJSONRequestBody = Credential
