openapi: "3.0.0"
info:
  version: 0.1.0
  title: sudo
  description: no
paths:
  /sudo/clusters:
    get:
      operationId: getClusters
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '../v1/spec.yaml#/components/schemas/cluster'
        500: {}
  /sudo/kubeconfigs/{cluster_id}:
    get:
      operationId: getKubeconfig
      parameters:
      - name: cluster_id
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
        500: {}
  /sudo/credentials/{credential_id}:
    get:
      operationId: getCredential
      parameters:
      - name: credential_id
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '../v1/spec.yaml#/components/schemas/credential'
        500: {}
