---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dockyards-io-v1alpha1-cluster
  failurePolicy: Fail
  name: validation.cluster.dockyards.io
  rules:
  - apiGroups:
    - dockyards.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-dockyards-io-v1alpha1-nodepool
  failurePolicy: Fail
  name: validation.nodepool.dockyards.io
  rules:
  - apiGroups:
    - dockyards.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - nodepools
  sideEffects: None
