// Package sudo provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.15.0 DO NOT EDIT.
package sudo

import (
	externalRef0 "bitbucket.org/sudosweden/dockyards-backend/api/v1"
)

// CreateDeploymentJSONRequestBody defines body for CreateDeployment for application/json ContentType.
type CreateDeploymentJSONRequestBody = externalRef0.Deployment

// CreateDeploymentStatusJSONRequestBody defines body for CreateDeploymentStatus for application/json ContentType.
type CreateDeploymentStatusJSONRequestBody = externalRef0.DeploymentStatus
